/*

 ANCIENTEVIL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ancientevilWidth 16
#define ancientevilHeight 2
#define ancientevilBank 0

extern unsigned char ancientevil[];

/* End of ANCIENTEVIL.H */
