/*

 CHRISDIALOGUE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chris1Width 11
#define chris1Height 2
#define chris1Bank 0

extern unsigned char chris1[];

/* End of CHRISDIALOGUE.H */
