/*

 JENNYDIALOGUE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define jenny1Width 16
#define jenny1Height 2
#define jenny1Bank 0

unsigned char jenny1[] =
{
  0x49,0x39,0x2E,0x48,0x52,0x2E,0x53,0x47,0x48,0x52,
  0x2E,0x2E,0x2E,0x2E,0x2E,0x2E,0x4F,0x4B,0x40,0x58,
  0x44,0x51,0x2E,0x48,0x4C,0x4F,0x40,0x42,0x53,0x48,
  0x4D,0x46
};

/* End of JENNYDIALOGUE.C */
