/*

 NOC.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8s

*/

#define nocWidth 16
#define nocHeight 2
#define nocBank 0

unsigned char noc[] =
{
  0x59,0x4F,0x55,0x2F,0x46,0x4F,0x55,0x4E,0x44,0x2F,
  0x54,0x48,0x45,0x2F,0x2F,0x2F,0x4B,0x45,0x59,0x2F,
  0x54,0x4F,0x2F,0x54,0x48,0x45,0x2F,0x4E,0x4F,0x43,
  0x2F,0x2F
};

/* End of NOC.C */
