/*

 NOCTEXT.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define noctextWidth 10
#define noctextHeight 2
#define noctextBank 0

unsigned char nocText[] =
{
  0x1E,0x1F,0x13,0x30,0x19,0x23,0x30,0x1E,0x1F,0x24,
  0x20,0x22,0x15,0x20,0x11,0x22,0x15,0x14,0x30,0x30
};

/* End of NOCTEXT.C */
