/*

 NOCTEXT2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 39
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define noctext2Width 10
#define noctext2Height 2
#define noctext2Bank 0

extern unsigned char noctext2[];

/* End of NOCTEXT2.H */
