/*

 NOCTEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define noctextWidth 10
#define noctextHeight 2
#define noctextBank 0

extern unsigned char noctext[];

/* End of NOCTEXT.H */
