/*

 PRESSSTART.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 1
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define starttextWidth 12
#define starttextHeight 1
#define starttextBank 0

unsigned char starttext[] =
{
  0x4F,0x51,0x44,0x52,0x52,0x86,0x52,0x53,0x40,0x51,
  0x53,0x86
};

/* End of PRESSSTART.C */
