/*

 QUESTION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define questionWidth 12
#define questionHeight 2
#define questionBank 0

extern unsigned char question[];

/* End of QUESTION.H */
