/*

 EAMONNS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char eamonns[] =
{
  0x84,0x07,0x0C,0x0F,0x1C,0x1F,0x3C,0x3F,
  0x27,0x27,0x23,0x23,0x68,0x68,0xA4,0xA4
};

/* End of EAMONNS.C */
