/*

 ANCIENTEVIL.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ancientevilWidth 16
#define ancientevilHeight 2
#define ancientevilBank 0

unsigned char ancientevil[] =
{
  0x49,0x54,0x2F,0x53,0x4D,0x45,0x4C,0x4C,0x53,0x2F,
  0x4C,0x49,0x4B,0x45,0x2F,0x2F,0x41,0x4E,0x43,0x49,
  0x45,0x4E,0x54,0x2F,0x45,0x56,0x49,0x4C,0x5D,0x5D,
  0x5D,0x2F
};

/* End of ANCIENTEVIL.C */
