/*

 CHRISDIALOGUE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chris1Width 11
#define chris1Height 2
#define chris1Bank 0

unsigned char chris1[] =
{
  0x2E,0x42,0x47,0x51,0x48,0x52,0x39,0x2E,0x2E,0x2E,
  0x2E,0x48,0x4C,0x2E,0x42,0x4E,0x4D,0x45,0x54,0x52,
  0x44,0x43
};

/* End of CHRISDIALOGUE.C */
