/*

 COIN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char coin[] =
{
  0x0C,0x0C,0x12,0x12,0x2F,0x2D,0x2B,0x29,
  0x27,0x25,0x2F,0x2D,0x1E,0x12,0x0C,0x0C
};

/* End of COIN.C */
