/*

 CONGRATULATIONS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define congratulationsWidth 20
#define congratulationsHeight 18
#define congratulationsBank 0

extern unsigned char congratulations[];

/* End of CONGRATULATIONS.H */
