/*

 GARLAND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define garlandWidth 16
#define garlandHeight 2
#define garlandBank 0

const unsigned char garland[] =
{
  0x42,0x55,0x52,0x49,0x45,0x44,0x2F,0x44,0x45,0x45,
  0x50,0x2F,0x2F,0x2F,0x2F,0x2F,0x55,0x4E,0x44,0x45,
  0x52,0x2F,0x47,0x41,0x52,0x4C,0x41,0x4E,0x44,0x5D,
  0x5D,0x2F
};

/* End of GARLAND.C */
