/*

 HEALTHBARMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 7 x 1
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\Assets\healthbar.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define healthbarmapWidth 7
#define healthbarmapHeight 1
#define healthbarmapBank 0

unsigned char healthbarmap[] =
{
  0xB7,0xB8,0xB8,0xB8,0xB8,0xB8,0xB9
};

/* End of HEALTHBARMAP.C */
