/*

 PERISH.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define perishWidth 16
#define perishHeight 2
#define perishBank 0

unsigned char perish[] =
{
  0x2F,0x59,0x4F,0x55,0x2F,0x57,0x49,0x4C,0x4C,0x2F,
  0x50,0x45,0x52,0x49,0x53,0x48,0x2F,0x4D,0x4F,0x52,
  0x54,0x41,0x4C,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2F
};

/* End of PERISH.C */
