/*

 PROFINTRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\Assets\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define profintroWidth 17
#define profintroHeight 2
#define profintroBank 0

extern unsigned char profintro[];

/* End of PROFINTRO.H */
