/*

 PROFINTRO.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\Assets\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define profintroWidth 17
#define profintroHeight 2
#define profintroBank 0

unsigned char profintro[] =
{
  0x50,0x52,0x4F,0x46,0x45,0x53,0x53,0x4F,0x52,0x2F,
  0x2F,0x45,0x4C,0x4C,0x49,0x53,0x3A,0x47,0x52,0x45,
  0x41,0x54,0x2F,0x41,0x44,0x56,0x45,0x4E,0x54,0x55,
  0x52,0x45,0x2F,0x2F
};

/* End of PROFINTRO.C */
