/*

 PROFLUCK.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\Assets\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define profluckWidth 17
#define profluckHeight 2
#define profluckBank 0

unsigned char profluck[] =
{
  0x41,0x48,0x45,0x41,0x44,0x2F,0x4F,0x46,0x2F,0x59,
  0x4F,0x55,0x5D,0x2F,0x2F,0x2F,0x2F,0x47,0x4F,0x4F,
  0x44,0x2F,0x4C,0x55,0x43,0x4B,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2F,0x2F,0x2F
};

/* End of PROFLUCK.C */
