/*

 PROFLUCK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\Assets\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define profluckWidth 17
#define profluckHeight 2
#define profluckBank 0

extern unsigned char profluck[];

/* End of PROFLUCK.H */
