/*

 SOPHIEDIALOGUE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sophie1Width 16
#define sophie1Height 2
#define sophie1Bank 0

unsigned char sophie1[] =
{
  0x47,0x44,0x4B,0x4F,0x2E,0x54,0x52,0x2E,0x4F,0x4B,
  0x44,0x40,0x52,0x44,0x2E,0x2E,0x56,0x4E,0x51,0x4B,
  0x43,0x2E,0x48,0x52,0x2E,0x4E,0x4D,0x2E,0x45,0x48,
  0x51,0x44
};

/* End of SOPHIEDIALOGUE.C */
