/*

 SOPHIEDIALOGUE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 47
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sophie1Width 16
#define sophie1Height 2
#define sophie1Bank 0

extern unsigned char sophie1[];

/* End of SOPHIEDIALOGUE.H */
