/*

 STARMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 18
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\stars.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 161
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define starmapWidth 64
#define starmapHeight 18
#define starmapBank 0

extern unsigned char starmap[];

/* End of STARMAP.H */
