/*

 TICKET2.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ticket2Width 16
#define ticket2Height 2
#define ticket2Bank 0

unsigned char ticket2[] =
{
  0x48,0x4D,0x2F,0x54,0x48,0x49,0x53,0x2F,0x54,0x49,
  0x43,0x4B,0x45,0x54,0x5D,0x5D,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2F
};

/* End of TICKET2.C */
