/*

 TICKET.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 2
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\alpha.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ticketWidth 16
#define ticketHeight 2
#define ticketBank 0

unsigned char ticket[] =
{
  0x50,0x4C,0x45,0x41,0x53,0x45,0x2F,0x54,0x41,0x4B,
  0x45,0x2F,0x2F,0x2F,0x2F,0x2F,0x54,0x48,0x49,0x53,
  0x2F,0x54,0x49,0x43,0x4B,0x45,0x54,0x2F,0x2F,0x2F,
  0x2F,0x2F
};

/* End of TICKET.C */
