/*

 TREEBACKGROUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 4
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\trees.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define treebackgroundWidth 2
#define treebackgroundHeight 4
#define treebackgroundBank 0

unsigned char treebackground[] =
{
  0x00,0x02,0x01,0x03,0x04,0x06,0x05,0x07
};

/* End of TREEBACKGROUND.C */
