/*

 TREEBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 4
   Tile set      : C:\Users\rpomykala\Documents\Jenny's Adventure\trees.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define treebackgroundWidth 2
#define treebackgroundHeight 4
#define treebackgroundBank 0

extern unsigned char treebackground[];

/* End of TREEBACKGROUND.H */
